// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4n7OJPwNu2cHce_b-Z5Pzw3KZZXp0WQ',
    appId: '1:229838729994:web:5a8eaa24e60764a255c0f3',
    messagingSenderId: '229838729994',
    projectId: 'flutter-recipes-app-25fa5',
    authDomain: 'flutter-recipes-app-25fa5.firebaseapp.com',
    storageBucket: 'flutter-recipes-app-25fa5.firebasestorage.app',
    measurementId: 'G-XQSKBNVJFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA05aGMnCZG4sM1ojbfFVeEHTsCJL8mYX0',
    appId: '1:229838729994:android:1bd3b602f18ac7e755c0f3',
    messagingSenderId: '229838729994',
    projectId: 'flutter-recipes-app-25fa5',
    storageBucket: 'flutter-recipes-app-25fa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsOOb6UXUB8dHTGaOVdu3GJmHW3hnFnrs',
    appId: '1:229838729994:ios:dd6cd97677081d8e55c0f3',
    messagingSenderId: '229838729994',
    projectId: 'flutter-recipes-app-25fa5',
    storageBucket: 'flutter-recipes-app-25fa5.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsOOb6UXUB8dHTGaOVdu3GJmHW3hnFnrs',
    appId: '1:229838729994:ios:dd6cd97677081d8e55c0f3',
    messagingSenderId: '229838729994',
    projectId: 'flutter-recipes-app-25fa5',
    storageBucket: 'flutter-recipes-app-25fa5.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg4n7OJPwNu2cHce_b-Z5Pzw3KZZXp0WQ',
    appId: '1:229838729994:web:5691b971d6da189355c0f3',
    messagingSenderId: '229838729994',
    projectId: 'flutter-recipes-app-25fa5',
    authDomain: 'flutter-recipes-app-25fa5.firebaseapp.com',
    storageBucket: 'flutter-recipes-app-25fa5.firebasestorage.app',
    measurementId: 'G-CDD3EBNJBQ',
  );
}
